finished es6-classes
kyle-foral/c0323-code-solutions pull request #63
Opened 2023-04-19 04:22 UTC by kyle-foral

![image](https://user-images.githubusercontent.com/126129416/232966396-a6be730b-9216-4065-8c8a-e999a93c0739.png)
![image](https://user-images.githubusercontent.com/126129416/232966408-5943e87d-d97e-4361-938b-d9607d775e8f.png)
![image](https://user-images.githubusercontent.com/126129416/232966420-051a41af-0db1-4676-b809-a0ac545e33ea.png)

2023-04-19 15:13 UTC, shawnkost commented on es6-classes/square.js
> +  constructor(width) { super(); }
You should also be defining `this.width` with the value that gets passed in from the `width` parameter

2023-04-19 15:13 UTC, shawnkost commented on es6-classes/square.js
> +const square = new Square();
When you instantiate `new Square()` you should be passing in an argument representing the `width`

2023-04-24 16:54 UTC, shawnkost requested changes
A few changes here Kyle!

2023-04-24 16:54 UTC, shawnkost commented on es6-classes/circle.js
> +    super(area, perimeter);
`area` and `perimeter` haven't been defined. You should be passing in a number here, utilizing your `radius` parameter.

2023-04-24 16:54 UTC, shawnkost commented on es6-classes/shape.js
> +const shape = new Shape();
You should be passing in 2 arguments here. One representing the `area` & the other `perimeter`

2023-04-24 16:54 UTC, shawnkost commented on es6-classes/square.js
> +    super(area, perimeter);
`area` and `perimeter` haven't been defined. You should be passing in a number here, utilizing your `width` parameter.

2023-06-06 14:42 UTC, RobertGardner approved these changes

2023-06-06 16:04 UTC, merged